[package]
name = "tundra"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
num-traits = "0.2.16"
ratatui = "0.24.0"
textwrap = "0.16.0"

[features]
default = ["managed_env"]
managed_env = []
